stages:
  - validate
  - deploy_to_test
  - deploy_to_prod
  - verify_deploy_to_test
  - verify_deploy_to_prod

lint:
  stage: validate
  image: kecorbin/ansible:devel
  script:
      - pip install f5-sdk
      - pip install bigsuds
      - apt update && apt install python-netaddr -y
      - apt install tree
      - tree
      #- ansible-playbook -i hosts --vault-password-file .vault_pass.txt failover_state_conditional.yml
      #- ansible-playbook debug_msg_test.yml -vvvv
      - ansible-playbook -i hosts --vault-password-file .vault_pass.txt as3-dr.yml -vvvvv
      - cat intended_config/192.168.122.223_as3.json
     # - cat intended_config/192.168.122.230_as3.json
      - tree


deploy_to_test:
    stage: deploy_to_test
    image: alpine:latest
    script:
     - echo "Deploy to test env"
     - apk add --update py-pip
     - apk add tree
     - apk add ansible
     - apk add python3
     - apk add openssh-client
     - tree
     - ansible-playbook -i hosts --vault-password-file .vault_pass.txt gather_facts.yml -vvvvv
     - ansible-playbook -i hosts --vault-password-file .vault_pass.txt as3.yml -vvvvv

    
  # environment:
  #   name: test
  # only:
  #   - test

# validate_test_environment:
#   image: ciscotestautomation/pyats:latest-robot
#   stage: verify_deploy_to_test
#   environment:
#     name: test
#   only:
#     - test
#   script:
#     - pwd
#     - cd tests
#     # important: need to add our current directory to PYTHONPATH
#     - export PYTHONPATH=$PYTHONPATH:$(pwd)
#     - robot --noncritical noncritical --variable testbed:./test_testbed.yml validation_tasks.robot

#   artifacts:
#       name: "pyats_robot_logs_${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
#       when: always
#       paths:
#         - ./tests/log.html
#         - ./tests/report.html
#         - ./tests/output.xml

# deploy_to_prod:
#   image: kecorbin/ansible:devel
#   stage: deploy_to_prod
#   script:
#     - echo "Deploy to prod env"
#     - ansible-playbook -i inventory/prod.yaml site.yaml
#   script:
#     - echo "Deploy to prod env"
#     - ansible-playbook -i inventory/prod.yaml site.yaml
#   environment:
#     name: production
#   only:
#     - production
#   when: manual
#   allow_failure: false
#   only:
#   - production

# validate_prod_environment:
#   image: ciscotestautomation/pyats:latest-robot
#   stage: verify_deploy_to_prod
#   dependencies:
#     - deploy_to_prod
#   only:
#     - production
#   script:
#     - pwd
#     - cd tests
#     - export PYTHONPATH=$PYTHONPATH:$(pwd)
#     - robot --noncritical noncritical --variable testbed:./prod_testbed.yml validation_tasks.robot
#   artifacts:
#       name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
#       when: always
#       paths:
#         - ./tests/log.html
#         - ./tests/report.html
#         - ./tests/output.xml