---
- name: LINKLIGHT AS3
  hosts: my_dg
  connection: local
  gather_facts: false

  vars:
    pool_members: "{{ groups['web'] }}"
    provider: 
       server: "{{ inventory_hostname }}"
       password: "{{ dg_password }}"
       user: root
       transport: cli
       validate_certs: False
    plane: a
    f5_api_un: admin

  vars_files:
    - group_vars/my_dg/data_model.yml

  tasks:
    - name: CREATE AS3 JSON BODY
      set_fact:
        as3_app_body: "{{ lookup('template','templates/F5App-BASE-JSON.j2', split_lines=False) }}"

    - name: generate F5 AS3 JSON config
      template:
        src: F5App-BASE-JSON.j2 
        dest: intended_config/{{ inventory_hostname }}_as3.json
      delegate_to: localhost



    - name: PUSH AS3
      uri:
        url: "https://{{ inventory_hostname }}/mgmt/shared/appsvcs/declare"
        method: POST
        body: "{{ lookup('template','templates/F5App-BASE-DR-JSON.j2', split_lines=False) }}"
        status_code: 200
        timeout: 300
        body_format: json
        force_basic_auth: true
        user: "{{ f5_api_un }}"
        password: "{{ dg_password }}"
        validate_certs: false
      delegate_to: localhost

# https://github.com/ansible/workshops/tree/master/exercises/ansible_f5