---

role_tenants:
#################################### FINANCE START ####################################
  finance:
    route_domain: 0
    applications:
#################################### APP-01 START ####################################
      finance_app01:
        class: Service_HTTPS
        virtualAddresses: 
          destination: 100.1.1.1/32
          port: 443
        lb_method: "round-robin"
        members:
          100.1.1.1:
            servicePort: 80
            adminState: enable 
          100.1.1.2:
            servicePort: 80
            adminState: enable
        monitor:
          sendpath: "/Ping.html"
          sendhost: "martin.org"
          receive: "Pong"
          username: "monitorUser"
          passphrase: "somethinghere"
#################################### APP-01 END   ####################################
#################################### APP-02 START ####################################
      finance_app02:
        class: Service_TCP
        virtualAddresses: 
          destination: 100.2.1.1/32
          port: 80
        lb_method: "round-robin"
        members:
          100.2.1.1:
            servicePort: 80
            adminState: enable 
          100.2.1.2:
            servicePort: 80
            adminState: enable
          100.2.1.3:
            servicePort: 80
            adminState: enable 
          100.2.1.4:
            servicePort: 80
            adminState: enable
          100.2.1.5:
            servicePort: 80
            adminState: enable 
          100.2.1.6:
            servicePort: 80
            adminState: enable
        monitor:
          sendpath: "/Ping.html"
          sendhost: "martin.org"
          receive: "Pong"
          username: "monitorUser"
          passphrase: "somethinghere"
#################################### APP-02 END   ####################################
######################################################################################
######################################################################################
#################################### HR START     ####################################
  hr:
    route_domain: 0
    applications:
#################################### APP-01 START ####################################
      hr_app01:
        class: Service_HTTP
        virtualAddresses: 
          destination: 101.1.1.1/32
          port: 80
        lb_method: "round-robin"
        members:
          101.1.1.1:
            servicePort: 80
            adminState: enable 
          101.1.1.2:
            servicePort: 80
            adminState: enable
        monitor:
          sendpath: "/Ping.html"
          sendhost: "martin.org"
          receive: "Pong"
          username: "monitorUser"
          passphrase: "somethinghere"
#################################### APP-01 END   ####################################
#################################### APP-02 START ####################################
      hr_app02:
        class: Service_TCP
        virtualAddresses: 
          destination: 101.2.1.1/32
          port: 80
        lb_method: "round-robin"
        members:
          101.2.1.1:
            servicePort: 80
            adminState: enable 
          101.2.1.2:
            servicePort: 80
            adminState: enable
        monitor:
          sendpath: "/Ping.html"
          sendhost: "martin.org"
          receive: "Pong"
          username: "monitorUser"
          passphrase: "somethinghere"
################################### APP-02 END   ####################################

#####################################################################################
#####################################################################################
#####################################################################################
#####################################################################################
################################### NETENG START ####################################
  net_eng:
    route_domain: 0
    applications:
#################################### APP-01 START ####################################
      net_eng_app01:
        class: Service_TCP
        virtualAddresses: 
          destination: 100.3.1.1/32
          port: 80
        lb_method: "round-robin"
        members:
          100.3.1.1:
            servicePort: 80
            adminState: enable 
          100.3.1.2:
            servicePort: 80
            adminState: enable
        monitor:
          sendpath: "/Ping.html"
          sendhost: "martin.org"
          receive: "Pong"
          username: "monitorUser"
          passphrase: "somethinghere"
#################################### APP-01 END   ####################################
#################################### APP-02 START ####################################
      net_eng_app02:
        class: Service_HTTP
        virtualAddresses: 
          destination: 100.3.2.1/32
          port: 80
        lb_method: "round-robin"
        members:
          100.3.3.1:
            servicePort: 80
            adminState: enable 
          100.3.2.2:
            servicePort: 80
            adminState: enable
          100.3.2.3:
            servicePort: 80
            adminState: enable 
          100.3.2.4:
            servicePort: 80
            adminState: enable
          100.3.2.5:
            servicePort: 80
            adminState: enable 
          10.10.10.10:
            servicePort: 80
            adminState: enable
        monitor:
          sendpath: "/Ping.html"
          sendhost: "martin.org"
          receive: "Pong"
          username: "monitorUser"
          passphrase: "somethinghere"
#################################### APP-02 END   ####################################
######################################################################################
######################################################################################